/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAssignmentsRouteImport } from './routes/admin/assignments'
import { Route as AdminCustomizationRouteImport } from './routes/admin/customization'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as TrainerQuizzesRouteImport } from './routes/trainer/quizzes'
import { Route as AdminMandatoryQuizzesIndexRouteImport } from './routes/admin/mandatory-quizzes.index'
import { Route as AdminMandatoryQuizzesQuizIdRouteImport } from './routes/admin/mandatory-quizzes.$quizId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports.index'
import { Route as AdminReportsReportIdRouteImport } from './routes/admin/reports.$reportId'
import { Route as ModulesModuleIdIndexRouteImport } from './routes/modules/$moduleId/index'
import { Route as ModulesModuleIdPlayerRouteImport } from './routes/modules/$moduleId/player'
import { Route as TrainerModulesModuleIdRouteImport } from './routes/trainer/modules.$moduleId'
import { Route as TrainerProgramsIndexRouteImport } from './routes/trainer/programs.index'
import { Route as TrainerProgramsProgramIdRouteImport } from './routes/trainer/programs.$programId'
import { Route as TrainerSkillsSkillIdRouteImport } from './routes/trainer/skills.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/admin/assignments',
  path: '/admin/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomizationRoute = AdminCustomizationRouteImport.update({
  id: '/admin/customization',
  path: '/admin/customization',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerQuizzesRoute = TrainerQuizzesRouteImport.update({
  id: '/trainer/quizzes',
  path: '/trainer/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMandatoryQuizzesIndexRoute =
  AdminMandatoryQuizzesIndexRouteImport.update({
    id: '/admin/mandatory-quizzes/',
    path: '/admin/mandatory-quizzes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMandatoryQuizzesQuizIdRoute =
  AdminMandatoryQuizzesQuizIdRouteImport.update({
    id: '/admin/mandatory-quizzes/$quizId',
    path: '/admin/mandatory-quizzes/$quizId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin/reports/',
  path: '/admin/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsReportIdRoute = AdminReportsReportIdRouteImport.update({
  id: '/admin/reports/$reportId',
  path: '/admin/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdIndexRoute = ModulesModuleIdIndexRouteImport.update({
  id: '/modules/$moduleId/',
  path: '/modules/$moduleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdPlayerRoute = ModulesModuleIdPlayerRouteImport.update({
  id: '/modules/$moduleId/player',
  path: '/modules/$moduleId/player',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerModulesModuleIdRoute = TrainerModulesModuleIdRouteImport.update({
  id: '/trainer/modules/$moduleId',
  path: '/trainer/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProgramsIndexRoute = TrainerProgramsIndexRouteImport.update({
  id: '/trainer/programs/',
  path: '/trainer/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProgramsProgramIdRoute =
  TrainerProgramsProgramIdRouteImport.update({
    id: '/trainer/programs/$programId',
    path: '/trainer/programs/$programId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainerSkillsSkillIdRoute = TrainerSkillsSkillIdRouteImport.update({
  id: '/trainer/skills/$skillId',
  path: '/trainer/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/certificates': typeof CertificatesRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/customization': typeof AdminCustomizationRoute
  '/admin/users': typeof AdminUsersRoute
  '/trainer/quizzes': typeof TrainerQuizzesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/mandatory-quizzes/$quizId': typeof AdminMandatoryQuizzesQuizIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/modules/$moduleId/player': typeof ModulesModuleIdPlayerRoute
  '/trainer/modules/$moduleId': typeof TrainerModulesModuleIdRoute
  '/trainer/programs/$programId': typeof TrainerProgramsProgramIdRoute
  '/trainer/skills/$skillId': typeof TrainerSkillsSkillIdRoute
  '/admin/mandatory-quizzes/': typeof AdminMandatoryQuizzesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/modules/$moduleId/': typeof ModulesModuleIdIndexRoute
  '/trainer/programs/': typeof TrainerProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/certificates': typeof CertificatesRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/customization': typeof AdminCustomizationRoute
  '/admin/users': typeof AdminUsersRoute
  '/trainer/quizzes': typeof TrainerQuizzesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/mandatory-quizzes/$quizId': typeof AdminMandatoryQuizzesQuizIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/modules/$moduleId/player': typeof ModulesModuleIdPlayerRoute
  '/trainer/modules/$moduleId': typeof TrainerModulesModuleIdRoute
  '/trainer/programs/$programId': typeof TrainerProgramsProgramIdRoute
  '/trainer/skills/$skillId': typeof TrainerSkillsSkillIdRoute
  '/admin/mandatory-quizzes': typeof AdminMandatoryQuizzesIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/modules/$moduleId': typeof ModulesModuleIdIndexRoute
  '/trainer/programs': typeof TrainerProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/certificates': typeof CertificatesRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/customization': typeof AdminCustomizationRoute
  '/admin/users': typeof AdminUsersRoute
  '/trainer/quizzes': typeof TrainerQuizzesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/mandatory-quizzes/$quizId': typeof AdminMandatoryQuizzesQuizIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/modules/$moduleId/player': typeof ModulesModuleIdPlayerRoute
  '/trainer/modules/$moduleId': typeof TrainerModulesModuleIdRoute
  '/trainer/programs/$programId': typeof TrainerProgramsProgramIdRoute
  '/trainer/skills/$skillId': typeof TrainerSkillsSkillIdRoute
  '/admin/mandatory-quizzes/': typeof AdminMandatoryQuizzesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/modules/$moduleId/': typeof ModulesModuleIdIndexRoute
  '/trainer/programs/': typeof TrainerProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/certificates'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/my-learning'
    | '/progress'
    | '/search'
    | '/admin/assignments'
    | '/admin/customization'
    | '/admin/users'
    | '/trainer/quizzes'
    | '/admin/'
    | '/admin/mandatory-quizzes/$quizId'
    | '/admin/reports/$reportId'
    | '/modules/$moduleId/player'
    | '/trainer/modules/$moduleId'
    | '/trainer/programs/$programId'
    | '/trainer/skills/$skillId'
    | '/admin/mandatory-quizzes/'
    | '/admin/reports/'
    | '/modules/$moduleId/'
    | '/trainer/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/certificates'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/my-learning'
    | '/progress'
    | '/search'
    | '/admin/assignments'
    | '/admin/customization'
    | '/admin/users'
    | '/trainer/quizzes'
    | '/admin'
    | '/admin/mandatory-quizzes/$quizId'
    | '/admin/reports/$reportId'
    | '/modules/$moduleId/player'
    | '/trainer/modules/$moduleId'
    | '/trainer/programs/$programId'
    | '/trainer/skills/$skillId'
    | '/admin/mandatory-quizzes'
    | '/admin/reports'
    | '/modules/$moduleId'
    | '/trainer/programs'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/certificates'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/my-learning'
    | '/progress'
    | '/search'
    | '/admin/assignments'
    | '/admin/customization'
    | '/admin/users'
    | '/trainer/quizzes'
    | '/admin/'
    | '/admin/mandatory-quizzes/$quizId'
    | '/admin/reports/$reportId'
    | '/modules/$moduleId/player'
    | '/trainer/modules/$moduleId'
    | '/trainer/programs/$programId'
    | '/trainer/skills/$skillId'
    | '/admin/mandatory-quizzes/'
    | '/admin/reports/'
    | '/modules/$moduleId/'
    | '/trainer/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CertificatesRoute: typeof CertificatesRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MyLearningRoute: typeof MyLearningRoute
  ProgressRoute: typeof ProgressRoute
  SearchRoute: typeof SearchRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminCustomizationRoute: typeof AdminCustomizationRoute
  AdminUsersRoute: typeof AdminUsersRoute
  TrainerQuizzesRoute: typeof TrainerQuizzesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMandatoryQuizzesQuizIdRoute: typeof AdminMandatoryQuizzesQuizIdRoute
  AdminReportsReportIdRoute: typeof AdminReportsReportIdRoute
  ModulesModuleIdPlayerRoute: typeof ModulesModuleIdPlayerRoute
  TrainerModulesModuleIdRoute: typeof TrainerModulesModuleIdRoute
  TrainerProgramsProgramIdRoute: typeof TrainerProgramsProgramIdRoute
  TrainerSkillsSkillIdRoute: typeof TrainerSkillsSkillIdRoute
  AdminMandatoryQuizzesIndexRoute: typeof AdminMandatoryQuizzesIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  ModulesModuleIdIndexRoute: typeof ModulesModuleIdIndexRoute
  TrainerProgramsIndexRoute: typeof TrainerProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customization': {
      id: '/admin/customization'
      path: '/admin/customization'
      fullPath: '/admin/customization'
      preLoaderRoute: typeof AdminCustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/quizzes': {
      id: '/trainer/quizzes'
      path: '/trainer/quizzes'
      fullPath: '/trainer/quizzes'
      preLoaderRoute: typeof TrainerQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mandatory-quizzes/': {
      id: '/admin/mandatory-quizzes/'
      path: '/admin/mandatory-quizzes'
      fullPath: '/admin/mandatory-quizzes/'
      preLoaderRoute: typeof AdminMandatoryQuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mandatory-quizzes/$quizId': {
      id: '/admin/mandatory-quizzes/$quizId'
      path: '/admin/mandatory-quizzes/$quizId'
      fullPath: '/admin/mandatory-quizzes/$quizId'
      preLoaderRoute: typeof AdminMandatoryQuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/admin/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/$reportId': {
      id: '/admin/reports/$reportId'
      path: '/admin/reports/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/': {
      id: '/modules/$moduleId/'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId/'
      preLoaderRoute: typeof ModulesModuleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/player': {
      id: '/modules/$moduleId/player'
      path: '/modules/$moduleId/player'
      fullPath: '/modules/$moduleId/player'
      preLoaderRoute: typeof ModulesModuleIdPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/modules/$moduleId': {
      id: '/trainer/modules/$moduleId'
      path: '/trainer/modules/$moduleId'
      fullPath: '/trainer/modules/$moduleId'
      preLoaderRoute: typeof TrainerModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/programs/': {
      id: '/trainer/programs/'
      path: '/trainer/programs'
      fullPath: '/trainer/programs/'
      preLoaderRoute: typeof TrainerProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/programs/$programId': {
      id: '/trainer/programs/$programId'
      path: '/trainer/programs/$programId'
      fullPath: '/trainer/programs/$programId'
      preLoaderRoute: typeof TrainerProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/skills/$skillId': {
      id: '/trainer/skills/$skillId'
      path: '/trainer/skills/$skillId'
      fullPath: '/trainer/skills/$skillId'
      preLoaderRoute: typeof TrainerSkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CertificatesRoute: CertificatesRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MyLearningRoute: MyLearningRoute,
  ProgressRoute: ProgressRoute,
  SearchRoute: SearchRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminCustomizationRoute: AdminCustomizationRoute,
  AdminUsersRoute: AdminUsersRoute,
  TrainerQuizzesRoute: TrainerQuizzesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMandatoryQuizzesQuizIdRoute: AdminMandatoryQuizzesQuizIdRoute,
  AdminReportsReportIdRoute: AdminReportsReportIdRoute,
  ModulesModuleIdPlayerRoute: ModulesModuleIdPlayerRoute,
  TrainerModulesModuleIdRoute: TrainerModulesModuleIdRoute,
  TrainerProgramsProgramIdRoute: TrainerProgramsProgramIdRoute,
  TrainerSkillsSkillIdRoute: TrainerSkillsSkillIdRoute,
  AdminMandatoryQuizzesIndexRoute: AdminMandatoryQuizzesIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  ModulesModuleIdIndexRoute: ModulesModuleIdIndexRoute,
  TrainerProgramsIndexRoute: TrainerProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
