/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ModulesModuleIdIndexRouteImport } from './routes/modules/$moduleId/index'
import { Route as ModulesModuleIdPlayerRouteImport } from './routes/modules/$moduleId/player'
import { Route as TrainerModulesModuleIdRouteImport } from './routes/trainer/modules.$moduleId'
import { Route as TrainerProgramsIndexRouteImport } from './routes/trainer/programs.index'
import { Route as TrainerProgramsProgramIdRouteImport } from './routes/trainer/programs.$programId'
import { Route as TrainerSkillsSkillIdRouteImport } from './routes/trainer/skills.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdIndexRoute = ModulesModuleIdIndexRouteImport.update({
  id: '/modules/$moduleId/',
  path: '/modules/$moduleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdPlayerRoute = ModulesModuleIdPlayerRouteImport.update({
  id: '/modules/$moduleId/player',
  path: '/modules/$moduleId/player',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerModulesModuleIdRoute = TrainerModulesModuleIdRouteImport.update({
  id: '/trainer/modules/$moduleId',
  path: '/trainer/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProgramsIndexRoute = TrainerProgramsIndexRouteImport.update({
  id: '/trainer/programs/',
  path: '/trainer/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProgramsProgramIdRoute =
  TrainerProgramsProgramIdRouteImport.update({
    id: '/trainer/programs/$programId',
    path: '/trainer/programs/$programId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainerSkillsSkillIdRoute = TrainerSkillsSkillIdRouteImport.update({
  id: '/trainer/skills/$skillId',
  path: '/trainer/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/modules/$moduleId/player': typeof ModulesModuleIdPlayerRoute
  '/trainer/modules/$moduleId': typeof TrainerModulesModuleIdRoute
  '/trainer/programs/$programId': typeof TrainerProgramsProgramIdRoute
  '/trainer/skills/$skillId': typeof TrainerSkillsSkillIdRoute
  '/modules/$moduleId/': typeof ModulesModuleIdIndexRoute
  '/trainer/programs/': typeof TrainerProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/modules/$moduleId/player': typeof ModulesModuleIdPlayerRoute
  '/trainer/modules/$moduleId': typeof TrainerModulesModuleIdRoute
  '/trainer/programs/$programId': typeof TrainerProgramsProgramIdRoute
  '/trainer/skills/$skillId': typeof TrainerSkillsSkillIdRoute
  '/modules/$moduleId': typeof ModulesModuleIdIndexRoute
  '/trainer/programs': typeof TrainerProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-learning': typeof MyLearningRoute
  '/progress': typeof ProgressRoute
  '/modules/$moduleId/player': typeof ModulesModuleIdPlayerRoute
  '/trainer/modules/$moduleId': typeof TrainerModulesModuleIdRoute
  '/trainer/programs/$programId': typeof TrainerProgramsProgramIdRoute
  '/trainer/skills/$skillId': typeof TrainerSkillsSkillIdRoute
  '/modules/$moduleId/': typeof ModulesModuleIdIndexRoute
  '/trainer/programs/': typeof TrainerProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificates'
    | '/leaderboard'
    | '/my-learning'
    | '/progress'
    | '/modules/$moduleId/player'
    | '/trainer/modules/$moduleId'
    | '/trainer/programs/$programId'
    | '/trainer/skills/$skillId'
    | '/modules/$moduleId/'
    | '/trainer/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificates'
    | '/leaderboard'
    | '/my-learning'
    | '/progress'
    | '/modules/$moduleId/player'
    | '/trainer/modules/$moduleId'
    | '/trainer/programs/$programId'
    | '/trainer/skills/$skillId'
    | '/modules/$moduleId'
    | '/trainer/programs'
  id:
    | '__root__'
    | '/'
    | '/certificates'
    | '/leaderboard'
    | '/my-learning'
    | '/progress'
    | '/modules/$moduleId/player'
    | '/trainer/modules/$moduleId'
    | '/trainer/programs/$programId'
    | '/trainer/skills/$skillId'
    | '/modules/$moduleId/'
    | '/trainer/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificatesRoute: typeof CertificatesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyLearningRoute: typeof MyLearningRoute
  ProgressRoute: typeof ProgressRoute
  ModulesModuleIdPlayerRoute: typeof ModulesModuleIdPlayerRoute
  TrainerModulesModuleIdRoute: typeof TrainerModulesModuleIdRoute
  TrainerProgramsProgramIdRoute: typeof TrainerProgramsProgramIdRoute
  TrainerSkillsSkillIdRoute: typeof TrainerSkillsSkillIdRoute
  ModulesModuleIdIndexRoute: typeof ModulesModuleIdIndexRoute
  TrainerProgramsIndexRoute: typeof TrainerProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/': {
      id: '/modules/$moduleId/'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId/'
      preLoaderRoute: typeof ModulesModuleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/player': {
      id: '/modules/$moduleId/player'
      path: '/modules/$moduleId/player'
      fullPath: '/modules/$moduleId/player'
      preLoaderRoute: typeof ModulesModuleIdPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/modules/$moduleId': {
      id: '/trainer/modules/$moduleId'
      path: '/trainer/modules/$moduleId'
      fullPath: '/trainer/modules/$moduleId'
      preLoaderRoute: typeof TrainerModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/programs/': {
      id: '/trainer/programs/'
      path: '/trainer/programs'
      fullPath: '/trainer/programs/'
      preLoaderRoute: typeof TrainerProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/programs/$programId': {
      id: '/trainer/programs/$programId'
      path: '/trainer/programs/$programId'
      fullPath: '/trainer/programs/$programId'
      preLoaderRoute: typeof TrainerProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/skills/$skillId': {
      id: '/trainer/skills/$skillId'
      path: '/trainer/skills/$skillId'
      fullPath: '/trainer/skills/$skillId'
      preLoaderRoute: typeof TrainerSkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificatesRoute: CertificatesRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyLearningRoute: MyLearningRoute,
  ProgressRoute: ProgressRoute,
  ModulesModuleIdPlayerRoute: ModulesModuleIdPlayerRoute,
  TrainerModulesModuleIdRoute: TrainerModulesModuleIdRoute,
  TrainerProgramsProgramIdRoute: TrainerProgramsProgramIdRoute,
  TrainerSkillsSkillIdRoute: TrainerSkillsSkillIdRoute,
  ModulesModuleIdIndexRoute: ModulesModuleIdIndexRoute,
  TrainerProgramsIndexRoute: TrainerProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
